/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package istiqomah;

/**
 *
 * @author Ammar Dzakwan
 */
public class Frame6WeeklyReport extends javax.swing.JFrame {
    //Panel panel;
    
    /**
     * Creates new form Frame1Salam
     */
    public Frame6WeeklyReport() {
        initComponents();
    }
    
    public Frame6WeeklyReport(int panel) {
        this.panelCuy = panel;
        initComponents();
        Check.setText(panel + "");
        //Panel = new panel();
        
    }
    
        int panelCuy;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGO = new javax.swing.JPanel();
        LOGOICON = new javax.swing.JLabel();
        Salam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Day1 = new javax.swing.JLabel();
        Day2 = new javax.swing.JLabel();
        Day3 = new javax.swing.JLabel();
        Day4 = new javax.swing.JLabel();
        Day5 = new javax.swing.JLabel();
        Day6 = new javax.swing.JLabel();
        PilihHariPertama = new javax.swing.JComboBox<>();
        Hari1 = new javax.swing.JLabel();
        Day7 = new javax.swing.JLabel();
        Hari2 = new javax.swing.JLabel();
        Hari3 = new javax.swing.JLabel();
        Hari4 = new javax.swing.JLabel();
        Hari5 = new javax.swing.JLabel();
        Hari6 = new javax.swing.JLabel();
        Hari7 = new javax.swing.JLabel();
        Done1 = new javax.swing.JLabel();
        Done2 = new javax.swing.JLabel();
        Done3 = new javax.swing.JLabel();
        Done4 = new javax.swing.JLabel();
        Done5 = new javax.swing.JLabel();
        Done6 = new javax.swing.JLabel();
        Done7 = new javax.swing.JLabel();
        Done8 = new javax.swing.JLabel();
        Done9 = new javax.swing.JLabel();
        Done10 = new javax.swing.JLabel();
        Done11 = new javax.swing.JLabel();
        Done12 = new javax.swing.JLabel();
        Done13 = new javax.swing.JLabel();
        Done14 = new javax.swing.JLabel();
        Done15 = new javax.swing.JLabel();
        Done16 = new javax.swing.JLabel();
        Done17 = new javax.swing.JLabel();
        Done18 = new javax.swing.JLabel();
        Done19 = new javax.swing.JLabel();
        Done20 = new javax.swing.JLabel();
        Done21 = new javax.swing.JLabel();
        Done22 = new javax.swing.JLabel();
        Done23 = new javax.swing.JLabel();
        Done24 = new javax.swing.JLabel();
        Done25 = new javax.swing.JLabel();
        Done26 = new javax.swing.JLabel();
        Done27 = new javax.swing.JLabel();
        Done28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SholCheck = new javax.swing.JLabel();
        SholCheck1 = new javax.swing.JLabel();
        SholCheck2 = new javax.swing.JLabel();
        SholCheck3 = new javax.swing.JLabel();
        SholCheck4 = new javax.swing.JLabel();
        SholCheck5 = new javax.swing.JLabel();
        SholCheck6 = new javax.swing.JLabel();
        Check = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOGOICON.setText("ISTIQOMAH");

        javax.swing.GroupLayout LOGOLayout = new javax.swing.GroupLayout(LOGO);
        LOGO.setLayout(LOGOLayout);
        LOGOLayout.setHorizontalGroup(
            LOGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGOLayout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(LOGOICON))
        );
        LOGOLayout.setVerticalGroup(
            LOGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGOLayout.createSequentialGroup()
                .addComponent(LOGOICON, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        Salam.setText("Weekly Report Habits");

        jLabel1.setText("Kamu bisa melihat progresmu disini : ");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lanjut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Day1.setText("Tilawah");

        Day2.setText("Sholawat");

        Day3.setText("Dzikir Pagi");

        Day4.setText("Dzikir Petang");

        Day5.setText("Jumlah Sholawat");

        Day6.setText("Jumlah Halaman");

        PilihHariPertama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu", "Minggu" }));
        PilihHariPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihHariPertamaActionPerformed(evt);
            }
        });

        Hari1.setText("Day 1");

        Day7.setText("Tilawah");

        Hari2.setText("Day 2");

        Hari3.setText("Day 3");

        Hari4.setText("Day 5");

        Hari5.setText("Day 4");

        Hari6.setText("Day 6");

        Hari7.setText("Day 7");

        Done1.setText("Done");

        Done2.setText("Done");

        Done3.setText("Done");

        Done4.setText("Done");

        Done5.setText("Done");

        Done6.setText("Done");

        Done7.setText("Done");

        Done8.setText("Done");

        Done9.setText("Done");

        Done10.setText("Done");

        Done11.setText("Done");

        Done12.setText("Done");

        Done13.setText("Done");

        Done14.setText("Done");

        Done15.setText("Done");

        Done16.setText("Done");

        Done17.setText("Done");

        Done18.setText("Done");

        Done19.setText("Done");

        Done20.setText("Done");

        Done21.setText("Done");

        Done22.setText("Done");

        Done23.setText("Done");

        Done24.setText("Done");

        Done25.setText("Done");

        Done26.setText("Done");

        Done27.setText("Done");

        Done28.setText("Done");

        jLabel2.setText("0 Hal");

        jLabel3.setText("0 Hal");

        jLabel4.setText("0 Hal");

        jLabel5.setText("0 Hal");

        jLabel6.setText("0 Hal");

        jLabel7.setText("0 Hal");

        jLabel8.setText("0 Hal");

        SholCheck.setText("0");

        SholCheck1.setText("0");

        SholCheck2.setText("0");

        SholCheck3.setText("0");

        SholCheck4.setText("0");

        SholCheck5.setText("0");

        SholCheck6.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PilihHariPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(Check, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Day2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Day1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Day4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(Day3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Day6))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Hari1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Hari2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Hari3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Hari5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Done1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Done8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Done15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Done22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Done23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Done24))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Done16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Done17))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Done9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Done10))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Done2)
                                                        .addGap(22, 22, 22)
                                                        .addComponent(Done3)))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Done4)
                                                    .addComponent(Done11)
                                                    .addComponent(Done18)
                                                    .addComponent(Done25)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(SholCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(SholCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(SholCheck2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(SholCheck3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Day5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Day7))
                                .addGap(43, 43, 43)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Hari4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addComponent(Done5)
                                .addComponent(Done12)
                                .addComponent(Done19)
                                .addComponent(Done26)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SholCheck4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Hari6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addComponent(Done6)
                                .addComponent(Done13)
                                .addComponent(Done20)
                                .addComponent(Done27)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SholCheck5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Hari7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SholCheck6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Done28)
                                    .addComponent(Done21)
                                    .addComponent(Done14)
                                    .addComponent(Done7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salam, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Salam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hari1)
                    .addComponent(Hari2)
                    .addComponent(Hari3)
                    .addComponent(Hari4)
                    .addComponent(Hari5)
                    .addComponent(Hari6)
                    .addComponent(Hari7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day1)
                    .addComponent(Done2)
                    .addComponent(Done3)
                    .addComponent(Done4)
                    .addComponent(Done5)
                    .addComponent(Done6)
                    .addComponent(Done7)
                    .addComponent(Done1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day2)
                    .addComponent(Done8)
                    .addComponent(Done9)
                    .addComponent(Done10)
                    .addComponent(Done11)
                    .addComponent(Done12)
                    .addComponent(Done13)
                    .addComponent(Done14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day3)
                    .addComponent(Done15)
                    .addComponent(Done16)
                    .addComponent(Done17)
                    .addComponent(Done18)
                    .addComponent(Done19)
                    .addComponent(Done20)
                    .addComponent(Done21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day4)
                    .addComponent(Done22)
                    .addComponent(Done23)
                    .addComponent(Done24)
                    .addComponent(Done25)
                    .addComponent(Done26)
                    .addComponent(Done27)
                    .addComponent(Done28))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(2, 2, 2)
                .addComponent(Day7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Day5)
                    .addComponent(SholCheck)
                    .addComponent(SholCheck1)
                    .addComponent(SholCheck2)
                    .addComponent(SholCheck3)
                    .addComponent(SholCheck4)
                    .addComponent(SholCheck5)
                    .addComponent(SholCheck6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(PilihHariPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (panelCuy == 1) {
            Frame3InfoTilawah f3 = new Frame3InfoTilawah();
        f3.setLocationRelativeTo(null);
        f3.setVisible(true);
        this.setVisible(false);
        } else if (panelCuy == 2) {
            Frame4InfoSholawat f4 = new Frame4InfoSholawat();
        f4.setLocationRelativeTo(null);
        f4.setVisible(true);
        this.setVisible(false);
        } else if (panelCuy == 3) {
            Frame5InfoDzikir f5 = new Frame5InfoDzikir();
        f5.setLocationRelativeTo(null);
        f5.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PilihHariPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihHariPertamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PilihHariPertamaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        switch (panelCuy) {
            case 1:
                Frame7TilawahPanel f7 = new Frame7TilawahPanel(panelCuy);
                f7.setLocationRelativeTo(null);
                f7.setVisible(true);
                this.setVisible(false);
                break;
            case 2:
                Frame8SholawatPanel f8 = new Frame8SholawatPanel(panelCuy);
                f8.setLocationRelativeTo(null);
                f8.setVisible(true);
                this.setVisible(false);
                break;
            case 3:
                Frame9DzikirPanel f9 = new Frame9DzikirPanel(panelCuy);
                f9.setLocationRelativeTo(null);
                f9.setVisible(true);
                this.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame6WeeklyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame6WeeklyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame6WeeklyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame6WeeklyReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame6WeeklyReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Check;
    private javax.swing.JLabel Day1;
    private javax.swing.JLabel Day2;
    private javax.swing.JLabel Day3;
    private javax.swing.JLabel Day4;
    private javax.swing.JLabel Day5;
    private javax.swing.JLabel Day6;
    private javax.swing.JLabel Day7;
    private javax.swing.JLabel Done1;
    private javax.swing.JLabel Done10;
    private javax.swing.JLabel Done11;
    private javax.swing.JLabel Done12;
    private javax.swing.JLabel Done13;
    private javax.swing.JLabel Done14;
    private javax.swing.JLabel Done15;
    private javax.swing.JLabel Done16;
    private javax.swing.JLabel Done17;
    private javax.swing.JLabel Done18;
    private javax.swing.JLabel Done19;
    private javax.swing.JLabel Done2;
    private javax.swing.JLabel Done20;
    private javax.swing.JLabel Done21;
    private javax.swing.JLabel Done22;
    private javax.swing.JLabel Done23;
    private javax.swing.JLabel Done24;
    private javax.swing.JLabel Done25;
    private javax.swing.JLabel Done26;
    private javax.swing.JLabel Done27;
    private javax.swing.JLabel Done28;
    private javax.swing.JLabel Done3;
    private javax.swing.JLabel Done4;
    private javax.swing.JLabel Done5;
    private javax.swing.JLabel Done6;
    private javax.swing.JLabel Done7;
    private javax.swing.JLabel Done8;
    private javax.swing.JLabel Done9;
    private javax.swing.JLabel Hari1;
    private javax.swing.JLabel Hari2;
    private javax.swing.JLabel Hari3;
    private javax.swing.JLabel Hari4;
    private javax.swing.JLabel Hari5;
    private javax.swing.JLabel Hari6;
    private javax.swing.JLabel Hari7;
    private javax.swing.JPanel LOGO;
    private javax.swing.JLabel LOGOICON;
    private javax.swing.JComboBox<String> PilihHariPertama;
    private javax.swing.JLabel Salam;
    private javax.swing.JLabel SholCheck;
    private javax.swing.JLabel SholCheck1;
    private javax.swing.JLabel SholCheck2;
    private javax.swing.JLabel SholCheck3;
    private javax.swing.JLabel SholCheck4;
    private javax.swing.JLabel SholCheck5;
    private javax.swing.JLabel SholCheck6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
